# Generated by Django 2.2.6 on 2020-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptname', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('scriptcontent', models.TextField(verbose_name='脚本内容')),
            ],
        ),
    ]
